
services:

  appdaf:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: appwoyofal
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_appwoyofal
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - appwoyofal
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_appwoyofal
    restart: always
    environment:
      POSTGRES_DB: appwoyofal_db
      POSTGRES_USER: woyofal_user
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_appdaf
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fatousha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin99
    ports:
      - "5052:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
